#!/usr/bin/env python3
"""Validate commit message style (English Conventional Commits).

Exit 0 = pass, 1 = fail. Usage:
  python3 translate/ops/check_commit_msg.py <path-to-COMMIT_EDITMSG>
  python3 translate/ops/check_commit_msg.py --stdin < message.txt
  git log -1 --format=%B | python3 translate/ops/check_commit_msg.py --stdin
"""

from __future__ import annotations

import argparse
import re
import sys

TYPES = (
    "feat",
    "fix",
    "docs",
    "chore",
    "ci",
    "test",
    "refactor",
    "sync",
    "translation",
    "quality",
)

SUBJECT_RE = re.compile(
    rf"^({'|'.join(TYPES)})"
    r"(\([a-z0-9][a-z0-9._/-]*\))?"
    r"!?"
    r": "
    r"([a-z0-9].{0,71})$"
)

# Non-Latin scripts (Cyrillic, CJK, Hangul, Arabic, Hebrew, …)
NON_LATIN_RE = re.compile(
    r"[\u0400-\u04FF\u0500-\u052F"  # Cyrillic
    r"\u4E00-\u9FFF\u3400-\u4DBF"  # CJK
    r"\u3040-\u30FF\uAC00-\uD7AF"  # Hiragana/Katakana/Hangul
    r"\u0600-\u06FF\u0590-\u05FF]"  # Arabic/Hebrew
)

CURSOR_ATTR_RE = re.compile(
    r"(?i)(co-authored-by:\s*cursor|made with\s*cursor|"
    r"cursoragent@|generated by\s*cursor)"
)

MERGE_RE = re.compile(r"^(Merge (pull request|branch|remote-tracking branch)|Revert \")")

MAX_SUBJECT = 72


def _strip_comments(text: str) -> str:
    """Drop git comment lines (# …) that appear in COMMIT_EDITMSG."""
    lines = []
    for line in text.splitlines():
        if line.startswith("#"):
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def validate(message: str) -> list[str]:
    """Return a list of error strings; empty means OK."""
    text = _strip_comments(message)
    if not text:
        return ["commit message is empty"]

    errors: list[str] = []
    lines = text.splitlines()
    subject = lines[0].strip()

    if MERGE_RE.match(subject):
        return []

    if CURSOR_ATTR_RE.search(text):
        errors.append(
            "Cursor/AI attribution trailers are not allowed "
            "(no Co-authored-by: Cursor, Made with Cursor, etc.)"
        )

    if NON_LATIN_RE.search(text):
        errors.append("message must be English only (no Cyrillic, CJK, or other non-Latin scripts)")

    if len(subject) > MAX_SUBJECT:
        errors.append(f"subject is {len(subject)} chars (max {MAX_SUBJECT})")

    if subject.endswith("."):
        errors.append("subject must not end with a period")

    m = SUBJECT_RE.match(subject)
    if not m:
        types = "|".join(TYPES)
        errors.append(
            "subject must match: "
            f"type(scope)?: description\n"
            f"  types: {types}\n"
            f"  scope: optional, lowercase [a-z0-9._/-]+\n"
            f"  description: starts with lowercase letter or digit, "
            f"imperative, English, ≤{MAX_SUBJECT} chars total subject"
        )
        return errors

    desc = m.group(3)
    if not desc or desc[0].isupper():
        errors.append("description must start with a lowercase letter or digit")

    # Blank line required between subject and body when body exists
    if len(lines) > 1 and lines[1].strip() != "":
        errors.append("insert a blank line between subject and body")

    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "path",
        nargs="?",
        help="path to COMMIT_EDITMSG (from commit-msg hook)",
    )
    parser.add_argument(
        "--stdin",
        action="store_true",
        help="read message from stdin",
    )
    args = parser.parse_args(argv)

    if args.stdin:
        message = sys.stdin.read()
    elif args.path:
        with open(args.path, encoding="utf-8") as f:
            message = f.read()
    else:
        parser.error("provide a path or --stdin")

    errors = validate(message)
    if errors:
        print("ERROR: commit message style check failed:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        print(
            "\nSee AGENTS.md → Commit messages. Examples:\n"
            "  translation(ru): kraken 2 (2019)\n"
            "  feat(pipeline): fetch PMC JATS XML\n"
            "  chore(pipeline): drop HTLB-only code",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
