title: "Extending and improving metagenomic taxonomic profiling with uncharacterized species using MetaPhlAn 4"
authors:
  - "Aitor Blanco-Míguez"
  - "Francesco Beghini"
  - "Fabio Cumbo"
  - "Lauren J. McIver"
  - "Kelsey N. Thompson"
  - "Moreno Zolfo"
  - "Paolo Manghi"
  - "Leonard Dubois"
  - "Kun D. Huang"
  - "Andrew Maltez Thomas"
  - "William A. Nickols"
  - "Gianmarco Piccinno"
  - "Elisa Piperni"
  - "Michal Punčochář"
  - "Mireia Valles-Colomer"
  - "Adrian Tett"
  - "Francesca Giordano"
  - "Richard Davies"
  - "Jonathan Wolf"
  - "Sarah E. Berry"
  - "Tim D. Spector"
  - "Eric A. Franzosa"
  - "Edoardo Pasolli"
  - "Francesco Asnicar"
  - "Curtis Huttenhower"
  - "Nicola Segata"
doi: "10.1038/s41587-023-01688-w"
pmcid: "PMC10635831"
journal: "Nature Biotechnology"
year: 2023
license: "CC BY 4.0"
status: "machine-translated"
zenodo-doi: ""
